AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
  DisabledByDefault: true

Performance:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/EmptyLineAfterMagicComment:
  Enabled: true
