dist: trusty
sudo: false
language: ruby
rvm:
  - "2.3"
  - "2.4"

language: node_js
node_js:
  - "6"

install:
  - gem install bundler
  - bundle check || bundle install
  - npm install

script:
  - bundle exec rake
  - bundle exec rubocop
