sudo: false
language: ruby
rvm:
  - "2.3"
  - "2.4"
addons:
  apt:
    packages:
      - node
before_install:
  - gem update bundler
  - npm install
script:
  - bundle exec rake
  - bundle exec rubocop
