dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7

install:
  - nvm install 10
  - npm install -g npm && npm --version
  - npm ci
  - gem update --system && gem --version
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

cache:
  bundler: true
  directories:
    - "$HOME/.npm"
    - vendor/bundle

script:
  - bundle exec rake
  - bundle exec rubocop
