dist: trusty
sudo: false
language: ruby
rvm:
  - "2.4"
  - "2.5"
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

install:
  - nvm install 8
  - npm install
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

cache:
  bundler: true
  directories:
    - node_modules
    - vendor/bundle

script:
  - bundle exec rake
  - bundle exec rubocop
