dist: trusty
sudo: false
language: ruby
rvm:
  - "2.4"
  - "2.5"
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - nvm install 8
  - npm install

cache:
  bundler: true
  directories:
    - node_modules

script:
  - bundle exec rake
  - bundle exec rubocop
